// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/api/extract.ts";
import * as $1 from "./routes/index.tsx";
import * as $$0 from "./islands/Playground.tsx";

const manifest = {
  routes: {
    "./routes/api/extract.ts": $0,
    "./routes/index.tsx": $1,
  },
  islands: {
    "./islands/Playground.tsx": $$0,
  },
  baseUrl: import.meta.url,
};

export default manifest;
