export const Samples = {
  time: `
    The earliest known tool for use in computation was the abacus, developed in the period between 2700 and 2300 BCE in Sumer.[3] The Sumerians' abacus consisted of a table of successive columns which delimited the successive orders of magnitude of their sexagesimal number system.[4]: 11  Its original style of usage was by lines drawn in sand with pebbles. Abaci of a more modern design are still used as calculation tools today, such as the Chinese abacus.[5] 

    In the 5th century BC in ancient India, the grammarian Pāṇini formulated the grammar of Sanskrit in 3959 rules known as the Ashtadhyayi which was highly systematized and technical. Panini used metarules, transformations and recursions.[6]

    The Antikythera mechanism is believed to be an early mechanical analog computer.[7] It was designed to calculate astronomical positions. It was discovered in 1901 in the Antikythera wreck off the Greek island of Antikythera, between Kythera and Crete, and has been dated to circa 100 BC.[7]

    Mechanical analog computer devices appeared again a thousand years later in the medieval Islamic world and were developed by Muslim astronomers, such as the mechanical geared astrolabe by Abū Rayhān al-Bīrūnī,[8] and the torquetum by Jabir ibn Aflah.[9] According to Simon Singh, Muslim mathematicians also made important advances in cryptography, such as the development of cryptanalysis and frequency analysis by Alkindus.[10][11] Programmable machines were also invented by Muslim engineers, such as the automatic flute player by the Banū Mūsā brothers,[12] and Al-Jazari's programmable castle clock, which is considered to be the first programmable analog computer.[disputed (for: The cited source doesn't support the claim, and the claim is misleading.)  – discuss][13] Technological artifacts of similar complexity appeared in 14th century Europe, with mechanical astronomical clocks.[14]

    When John Napier discovered logarithms for computational purposes in the early 17th century,[15] there followed a period of considerable progress by inventors and scientists in making calculating tools. In 1623 Wilhelm Schickard designed a calculating machine, but abandoned the project, when the prototype he had started building was destroyed by a fire in 1624.[16] Around 1640, Blaise Pascal, a leading French mathematician, constructed a mechanical adding device based on a design described by Greek mathematician Hero of Alexandria.[17] Then in 1672 Gottfried Wilhelm Leibniz invented the Stepped Reckoner which he completed in 1694.[18]

    In 1837 Charles Babbage first described his Analytical Engine which is accepted as the first design for a modern computer. The analytical engine had expandable memory, an arithmetic unit, and logic processing capabilities able to interpret a programming language with loops and conditional branching. Although never built, the design has been studied extensively and is understood to be Turing equivalent. The analytical engine would have had a memory capacity of less than 1 kilobyte of memory and a clock speed of less than 10 Hertz.[19]

    Considerable advancement in mathematics and electronics theory was required before the first modern computers could be designed.
  `,
  temperature: `
    Most of Europe sees seasonal temperatures consistent with temperate climates in other parts of the world, though summers north of the Mediterranean Sea are cooler than most temperate climates experience in summer. Among the cities with a population over 100,000 people in Europe, the coldest winters are mostly found in Russia, with daily highs in winter averaging 0 °C (32 °F), while the mildest winters in the continent are in southern Portugal, southern Spain, in Sicily (Italy) and southern Greek islands such as Crete, Rhodes, Karpathos and Kasos.
    The hottest summers of the continent occur in cities and towns of the hinterland of southern Spain and southern Greece. July average highs in Spain are 36.9 °C (98.4 °F) in Cordoba and 36.0 °C (96.8 °F) in Seville. July and August highs in Greece average around 35.8 °C (96.4 °F) in Sparta and Gavalou. The highest extreme temperatures have been recorded in Athens with 48.0 °C (118.4 °F)[6] and inside the southern valleys of the Iberian Peninsula, with towns such as Amareleja (Portugal) and Montoro (Spain) recording temperatures of 47.4 °C (117.3 °F)[7] and 47.3 °C (117.1 °F)[8] respectively. 
   `,
};
